### ISSUE TITLE
Erro Deprecated

### ISSUE THREAD

**Issue by DX-BR** [erandirjunior/plug-route#52]
Olá estou com erro ao colocar o meu projeto em um hospedagem ficou com erro mais rodando local no xamp não apresentou.

```
Deprecated: Required parameter $route follows optional parameter $types in /storage/ssd4/128/17690128/public_html/vendor/erandir/plug-route/src/RouteContainer.php on line 258

Deprecated: Required parameter $callback follows optional parameter $types in /storage/ssd4/128/17690128/public_html/vendor/erandir/plug-route/src/RouteContainer.php on line 258

Fatal error: Uncaught Exception: Error: class core\models\users don't exists. in /storage/ssd4/128/17690128/public_html/vendor/erandir/plug-route/src/Error.php:9 Stack trace: #0 /storage/ssd4/128/17690128/public_html/vendor/erandir/plug-route/src/Callback/Reflection.php(41): PlugRoute\Error::throwException() #1 /storage/ssd4/128/17690128/public_html/vendor/erandir/plug-route/src/Callback/Callback.php(56): PlugRoute\Callback\Reflection->callClass() #2 /storage/ssd4/128/17690128/public_html/vendor/erandir/plug-route/src/Callback/Callback.php(35): PlugRoute\Callback\Callback->handlerObject() #3 /storage/ssd4/128/17690128/public_html/vendor/erandir/plug-route/src/RouteManager.php(39): PlugRoute\Callback\Callback->handlerCallback() #4 /storage/ssd4/128/17690128/public_html/vendor/erandir/plug-route/src/PlugRoute.php(135): PlugRoute\RouteManager->run() #5 /storage/ssd4/128/17690128/public_html/core/controller/routes.php(124): PlugRoute\PlugRoute->on() #6 /storage/ssd4/128/17690128/public_html/index.php(15): require_once('...') #7 {main} thrown in /storage/ssd4/128/17690128/public_html/vendor/erandir/plug-route/src/Error.php on line 9
```
![Capturar](https://user-images.githubusercontent.com/49926091/135630357-372c2d7e-a652-4d26-999d-2bb849f3d3c5.PNG)

**Comment by erandirjunior** [comment]
Qual a versão que você está utilizando?

**Comment by erandirjunior** [comment]
Acabei de subir uma versão nova que corrige esse erro @DX-BR.

**Comment by DX-BR** [comment]
Obrigado meu amigo !

**Comment by gusbemacbe** [comment]
Boa noite, @erandirjunior 

O teu pacote é compatível com a versão 8?

Outro erro, acredito ser depreciado:

```
[Mon Feb 21 00:48:38 2022] PHP Fatal error:  Uncaught Error: Class "PlugHttp\Get" not found in /home/gusbemacbe/GitLab/Outros/th-producoes/vendor/erandir/plug-route/src/Http/RequestCreator.php:17
Stack trace:
#0 /home/gusbemacbe/GitLab/Outros/th-producoes/App/Routes/web.php(7): PlugRoute\Http\RequestCreator::create()
#1 /home/gusbemacbe/GitLab/Outros/th-producoes/public/index.php(5): require_once('...')
#2 {main}
  thrown in /home/gusbemacbe/GitLab/Outros/th-producoes/vendor/erandir/plug-route/src/Http/RequestCreator.php on line 17
[Mon Feb 21 00:48:38 2022] [::1]:58416 [200]: GET / - Uncaught Error: Class "PlugHttp\Get" not found in /home/gusbemacbe/GitLab/Outros/th-producoes/vendor/erandir/plug-route/src/Http/RequestCreator.php:17
Stack trace:
#0 /home/gusbemacbe/GitLab/Outros/th-producoes/App/Routes/web.php(7): PlugRoute\Http\RequestCreator::create()
#1 /home/gusbemacbe/GitLab/Outros/th-producoes/public/index.php(5): require_once('...')
#2 {main}
  thrown in /home/gusbemacbe/GitLab/Outros/th-producoes/vendor/erandir/plug-route/src/Http/RequestCreator.php on line 17
```

E o pequeno código:

```php
<?php

use PlugRoute\Http\RequestCreator;
use PlugRoute\PlugRoute;
use PlugRoute\RouteContainer;

$route = new PlugRoute(new RouteContainer(), RequestCreator::create());
```

Baseado no projecto de @lucas-ayabe.
