### ISSUE TITLE
Erros de depreciação

### ISSUE THREAD

**Issue by gusbemacbe** [erandirjunior/plug-route#54]
Boa noite, @erandirjunior

O teu pacote é compatível com a versão 8?

Outro erro, acredito ser depreciado:

```
[Mon Feb 21 00:48:38 2022] PHP Fatal error:  Uncaught Error: Class "PlugHttp\Get" not found in /home/gusbemacbe/GitLab/Outros/th-producoes/vendor/erandir/plug-route/src/Http/RequestCreator.php:17
Stack trace:
#0 /home/gusbemacbe/GitLab/Outros/th-producoes/App/Routes/web.php(7): PlugRoute\Http\RequestCreator::create()
#1 /home/gusbemacbe/GitLab/Outros/th-producoes/public/index.php(5): require_once('...')
#2 {main}
  thrown in /home/gusbemacbe/GitLab/Outros/th-producoes/vendor/erandir/plug-route/src/Http/RequestCreator.php on line 17
[Mon Feb 21 00:48:38 2022] [::1]:58416 [200]: GET / - Uncaught Error: Class "PlugHttp\Get" not found in /home/gusbemacbe/GitLab/Outros/th-producoes/vendor/erandir/plug-route/src/Http/RequestCreator.php:17
Stack trace:
#0 /home/gusbemacbe/GitLab/Outros/th-producoes/App/Routes/web.php(7): PlugRoute\Http\RequestCreator::create()
#1 /home/gusbemacbe/GitLab/Outros/th-producoes/public/index.php(5): require_once('...')
#2 {main}
  thrown in /home/gusbemacbe/GitLab/Outros/th-producoes/vendor/erandir/plug-route/src/Http/RequestCreator.php on line 17
```

E o pequeno código:

```php
<?php

use PlugRoute\Http\RequestCreator;
use PlugRoute\PlugRoute;
use PlugRoute\RouteContainer;

$route = new PlugRoute(new RouteContainer(), RequestCreator::create());
```

Baseado no projecto de @Lucas-Ayabe.

**Comment by erandirjunior** [comment]
@gusbemacbe eu passei um tempo muito ocupado, porém fiz uma refatoração gigante da aplicação, adicionei mais testes, removi umas coisas e não percebi algum erro do tipo.
